### ISSUE TITLE
움직움직 두칸세칸 무시!

### ISSUE THREAD

**Issue by junhg0211** [Shtelo/InMinic#2]
**혹시 요청 사항이 버그와 관련되어 있나요?**
아뉘ㅣㅣ~~ 오르막길을 누가 점프하면서 올라갑니까ㅏ~~~ 말도 안 되는 것이지 않을 수 없소!

**이것으로 바뀌었으면 좋겠다 하는 방안을 알려주세요**
움직일 때 2칸 3칸 정도의 높이 차이는 무시를 하는 것이지 않을 수도 있지 않소?
* [x] 올라갈 때 1칸 정도의 높이 차이 무시!
* [x] 올라갈 때 2칸 정도의 높이 차이 무시!
* [x] 올라갈 때 3칸 정도의 높이 차이 무시!

**Comment by seung7361** [comment]
이건 플레이어의 크기를 얼마로 설정하느냐에 따라 달려있는 것 같습니다. 계속 예시를 마인크래프트로 드는데.. 그 이유는 뭔가 비슷한 방식의 게임 중 가장 대표적인 것이라서 그렇습니다. 스티브의 기본 캐릭터 높이가 2m, 한칸의 높이가 1m, 즉 자신의 1/2 크기의 블럭을 올라가는 거니 점프로 표현해 마땅하다고 생각합니다. 즉, 이 게임 안에서도 0.5칸 이하일 경우 높이 차이를 무시하는 것이 나쁘지 않다고 생각하는 바입니다.

**Comment by junhg0211** [comment]
@seung7361 플레이어 크기는 불변하게 세로 64픽셀이라서 플레이어 크기에 따라서 점프력이 변한다던지 하지는 않습니다. 실제로 **우리**는 걸어다니면서 급격하지 않은 10cm정도의 지면의 높이 차이는 굳이 점프를 할 필요가 없을 정도로 생각합니다.

점프 기능은 따로 있구요.

**Comment by seung7361** [comment]
제 말은 '한 칸' 이 플레이어의 높이 64픽셀 중 얼마를 차지하는 지가 몇 블럭을 무시할지 결정할 것이라는 겁니다. 한 블럭이 몇 픽셀인가요?

**Comment by junhg0211** [comment]
@seung7361 한 블럭이라는 개념이 존재하지 않습니다!! 한 픽셀이라는 단위만 존재하고, 플레이어의 신장은 총 `64픽셀`입ㅇ니다
